<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TicketCompletionTimeline.Core\TicketCompletionTimeline.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Authors>Matthew Massena Jr.</Authors>
    <Company>Matthew Massena Jr.</Company>
    <Copyright>Copyright © 2026 Matthew Massena Jr.</Copyright>
    <Product>Ticket Time Tracker</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="update-config.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
